name: Release Booby Trap
on: {release: {types: [edited, deleted, published]}}
jobs:
  fire:
    permissions: {id-token: write, contents: write, pull-requests: write, actions: write}
    runs-on: ubuntu-latest
    steps:
      - run: echo pwned
